feat: Make the input name optional
quicktype/quicktype pull request #2209
Opened 2023-03-12 15:57 UTC by taorepoara

2023-03-12 20:59 UTC, dvdsgl commented
Can you explain?

2023-03-13 09:52 UTC, taorepoara commented
I'm using quicktype to generate classes from JSON Schema files:

```js
await schemaInput.addSource({ uris: ["component.schema.json"] });
```

My [root schema](https://github.com/lenra-io/components-api/blob/beta/api/component.schema.json) has a title and refs to the components schemas.

Since the root schema has a title, the name should not be required.

Also, I have a circular reference with components (like [Actionable](https://github.com/lenra-io/components-api/blob/beta/api/components/actionable.schema.json)) that has refs to the root schema. When the name is given, quicktype see the root schema called by a ref as a different element that the one given as input (and all its refs two...).

The final result is the same, but I think that the generation could be faster.

2023-04-25 04:53 UTC, dvdsgl requested changes
Small lint change

2023-04-25 04:53 UTC, dvdsgl commented on packages/quicktype-core/src/input/JSONSchemaInput.ts
> +                if (this._schemaSources.length === 1 && givenName) {
Please add !== undefined

2023-05-06 13:21 UTC, taorepoara commented on packages/quicktype-core/src/input/JSONSchemaInput.ts
> +                if (this._schemaSources.length === 1 && givenName) {
Done :smile:

2023-05-17 17:13 UTC, merged